on: push
tags:
  - '*'
name: Build Angular
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest"
          message: "Latest release"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.12.1]

    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install 
        run:  npm ci
      - name: npm build
        run:  npm run build:ci
      - name: Push Build to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/app/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          